# Generated by Django 2.0.2 on 2018-05-10 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('last_error_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentType',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='environment',
            name='environment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms.EnvironmentType'),
        ),
    ]
